export const FETCH_MY_PROFILE = "FETCH_MY_PROFILE";
export const FETCH_MY_PROFILE_REQUEST = `${FETCH_MY_PROFILE}.request`;
export const FETCH_MY_PROFILE_SUCCESS = `${FETCH_MY_PROFILE}.success`;
export const FETCH_MY_PROFILE_FAILED = `${FETCH_MY_PROFILE}.failed`;

export const SET_ACTIVE_FRIEND_PROFILE = "SET_ACTIVE_FRIEND_PROFILE";
export const SET_ACTIVE_FRIEND_PROFILE_SUCCESS = `${SET_ACTIVE_FRIEND_PROFILE}.success`;
export const SET_ACTIVE_FRIEND_PROFILE_RESET = `${SET_ACTIVE_FRIEND_PROFILE}.reset`;
